import type { AnalysisResponse, DecisionLab as DecisionLabData } from "@/types/analysis";

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const clamp = (value: number) => Math.min(100, Math.max(0, value));
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

function Meter({ label, value, kind = "positive" }: { label: string; value: number; kind?: "positive" | "warning" | "negative" }) {
  return <div className="lab-meter"><div><span>{label}</span><strong>{value}%</strong></div><div className="lab-track" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><span className={kind} style={{ width: `${clamp(value)}%` }}/></div></div>;
}
function EmptyList({ items, empty }: { items?: string[]; empty: string }) { return items?.length ? <ul className="lab-list">{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p className="lab-empty">✓ {empty}</p>; }
function Comparison({ label, before, after }: { label: string; before: number; after: number }) { const delta = after - before; return <article className="lab-comparison"><span>{label}</span><div><strong>{before}</strong><span aria-hidden="true">→</span><strong>{after}</strong></div><small>{delta === 0 ? "No change" : `${delta > 0 ? "+" : ""}${delta} points`}</small></article>; }

export function DecisionLab({ data, analysis, preview }: { data: DecisionLabData; analysis: AnalysisResponse; preview: boolean }) {
  const totalVotes = data.committee.support + data.committee.oppose + data.committee.abstain;
  const confidenceDrop = Math.max(0, data.stress_test.normal_confidence - data.stress_test.stressed_confidence);
  return <section className="decision-lab" id="decision-lab" aria-labelledby="decision-lab-title">
    <header className="lab-header"><div><p className="eyebrow">Adversarial decision intelligence</p><h2 id="decision-lab-title">Decision Laboratory</h2><p className="lab-id">{data.investigation_id} · {analysis.symbol}</p></div><div className="lab-header-status">{preview && <span className="preview-label">Demo preview</span>}<span>Runtime mode disclosed below · not financial advice</span></div></header>
    <div className="lab-event"><div><span>Detected event</span><h3>{data.event.title}</h3><p>{data.event.description}</p></div><div className="lab-final"><span>Final market view</span><strong>{titleCase(analysis.synthesis.classification)}</strong><b>{analysis.synthesis.confidence}% confidence</b></div></div>
    {(analysis.synthesis.conflicts?.length ?? 0) > 0 && <div className="lab-conflict-note"><strong>Conflict is active in this analysis.</strong><span>{analysis.synthesis.conflicts.length} disclosed disagreement{analysis.synthesis.conflicts.length === 1 ? "" : "s"}.</span></div>}
    <div className="lab-grid lab-grid-top"><section className="lab-card"><div className="lab-card-heading"><div><p className="eyebrow">Agent committee</p><h3>How the committee voted</h3></div><span>{totalVotes} votes</span></div><div className="vote-grid"><div><strong>{data.committee.support}</strong><span>Support</span></div><div><strong>{data.committee.oppose}</strong><span>Oppose</span></div><div><strong>{data.committee.abstain}</strong><span>Abstain</span></div></div><Meter label="Consensus score" value={data.committee.consensus_score}/><Meter label="Fragility score" value={data.committee.fragility_score} kind="warning"/></section>
      <section className="lab-card advocate-card"><div className="lab-card-heading"><div><p className="eyebrow">Challenge</p><h3>Devil’s Advocate</h3></div><span className="lab-signal">{titleCase(data.devils_advocate.signal)} · {data.devils_advocate.confidence}%</span></div><blockquote>{data.devils_advocate.challenge}</blockquote><h4>Evidence behind the challenge</h4><EmptyList items={data.devils_advocate.evidence} empty="No challenge evidence supplied"/></section></div>
    <div className="lab-grid"><section className="lab-card"><p className="eyebrow">Evidence verification</p><h3>Claim coverage</h3><Meter label="Evidence coverage" value={data.evidence_verification.coverage_score}/><p className="claim-count"><strong>{data.evidence_verification.verified_claims}</strong> of <strong>{data.evidence_verification.total_claims}</strong> claims verified</p><h4>Unsupported claims</h4><EmptyList items={data.evidence_verification.unsupported_claims} empty="No unsupported claims identified"/></section>
      <section className="lab-card"><p className="eyebrow">Intelligence gaps</p><h3>What remains unknown</h3><div className="penalty"><strong>−{data.missing_information.confidence_penalty}</strong><span>point confidence penalty</span></div><EmptyList items={data.missing_information.gaps} empty="No gaps detected"/></section></div>
    <section className="lab-card lab-wide"><div className="lab-card-heading"><div><p className="eyebrow">Decision DNA</p><h3>Factors behind the view</h3></div><span>Weighted influence</span></div><div className="dna-list">{(data.decision_dna ?? []).map((item) => <div key={item.factor}><div><span>{item.factor}</span><strong>{item.weight}%</strong></div><div className="dna-track"><span style={{ width: `${clamp(item.weight)}%` }}/></div></div>)}{!data.decision_dna?.length && <p className="lab-empty">No factor weights available</p>}</div></section>
    <section className="lab-card lab-wide"><p className="eyebrow">Invalidation checklist</p><h3>What would change our mind?</h3><div className="mind-grid">{(data.change_our_mind ?? []).map((item, index) => <article key={`${item}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></article>)}{!data.change_our_mind?.length && <p className="lab-empty">No invalidation conditions supplied</p>}</div></section>
    <div className="lab-grid"><section className="lab-card"><p className="eyebrow">Confidence stress test</p><h3>Remove the strongest evidence</h3><div className="stress-pair"><div><span>Normal</span><strong>{titleCase(data.stress_test.normal_signal)}</strong><b>{data.stress_test.normal_confidence}%</b></div><span aria-hidden="true">→</span><div><span>Stressed</span><strong>{titleCase(data.stress_test.stressed_signal)}</strong><b>{data.stress_test.stressed_confidence}%</b></div></div><div className="confidence-drop"><strong>−{confidenceDrop} points</strong><span>{titleCase(data.stress_test.robustness)} robustness</span></div><p className="removed-evidence"><span>Evidence removed</span>{data.stress_test.removed_evidence}</p></section>
      <section className="lab-card"><div className="lab-card-heading"><div><p className="eyebrow">Counterfactual simulator</p><h3>{money(data.counterfactual.investment_amount)} simulated investment</h3></div><span className="preview-label">Simulation</span></div><div className="comparison-grid"><Comparison label="Risk" before={data.counterfactual.risk_before} after={data.counterfactual.risk_after}/><Comparison label="Sector exposure" before={data.counterfactual.sector_exposure_before} after={data.counterfactual.sector_exposure_after}/><Comparison label="Diversification" before={data.counterfactual.diversification_before} after={data.counterfactual.diversification_after}/></div><p className="interpretation">{data.counterfactual.interpretation}</p></section></div>
    <section className="lab-card lab-wide"><div className="lab-card-heading"><div><p className="eyebrow">Audit trail</p><h3>Decision replay</h3></div><span>Ordered system events, not chain-of-thought</span></div>{data.replay?.length ? <ol className="replay-list">{[...data.replay].sort((a, b) => a.order - b.order).map((item) => <li className={`replay-${item.status}`} key={`${item.order}-${item.stage}`}><span className="replay-marker">{item.order}</span><div><div><strong>{titleCase(item.stage)}</strong><span>{titleCase(item.status)}</span></div><p>{item.message}</p></div></li>)}</ol> : <p className="lab-empty">No replay events available</p>}</section>
  </section>;
}
